### ISSUE TITLE
Merge order 

### ISSUE THREAD

**Issue by jdk24** [meggsimum/sauber-sdi-docker#72]
Out of PRs #63, #64, #71 the preferred merge order is 

- [x] #64 (ideally after collecting all immediate DB changes for now)
- [x] #71 after the previous PR changed the raster_metadata table.
- [x] #63 to download LUBW measures. Not urgent.
- [x] #97 
- [x] #96 
- [x] #98
- [x] #61 once it is implemented based on #71
- [x] #117 tested and approved
- [x] #113 remove prop path: No dependencies
- [x]  #127
- [x] #120 
- [x] #126
- [x] #121 ideally when no more changes in sight

**Comment by chrismayer** [comment]
Removed #122 (DB Backup) from the list since this is more a standalone task.

After the list above is complete, we can do a deployment to the test system and close this issue.

**Comment by jdk24** [comment]
Closed as all PRs were merged as of now and running on server. 🎉

**Comment by chrismayer** [comment]
Great teamwork :muscle: :tada: :+1: Thank you all!
